CREATE TABLE projeto (
NUMERO INTEGER KEY ORD,
NOME_P STRING);

CREATE TABLE casa(
CODIGO_E STRING KEY ORD,
NOME_E STRING,
SALARIO INTEGER,
NUM_PROJ INTEGER FK projeto);

CREATE TABLE produto (
CODIGO_PR STRING KEY ORD,
NOME STRING,
COR STRING);

